server:
  port: ${PORT:${SERVER_PORT:0}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/routinecart_order
    username: routinecart
    password: routinecart